version: "2"

services:
  mags-server:
    image: mags-server
    container_name: mags-server
    depends_on:
      - mags-postgresql
    environment:
        - _JAVA_OPTIONS=-Xmx512m -Xms256m
        - SPRING_PROFILES_ACTIVE=local, docker
        - SPRING_DATASOURCE_URL=jdbc:postgresql://mags-postgresql:5432/compose-postgres
        - SPRING_DATASOURCE_USERNAME=compose-postgres
        - SPRING_DATASOURCE_PASSWORD=compose-postgres
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    expose:
      - "8080"
    volumes:
    - ./mags-data/:/mags-data/

  mags-ui:
    image: mags-ui
    container_name: mags-ui
    ports:
      - 8090:8090
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=local, docker

  mags-postgresql:
    extends:
      file: postgresql.yml
      service: mags-postgresql

volumes:
  pgdata: