version: "2"

services:
  mags-postgresql:
    image: 'postgres:13.1-alpine'
    container_name: mags-postgresql
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    expose:
      - "5432"
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
